[package]
name = "trayracer"
version = "0.1.0"
authors = ["smudgecat123 <jf14218@my.bristol.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.32.1"
ash-window = "0.6.0"
winit = "0.24.0"
libc = "0.2"